from time import sleep
count = 0
while count < 20:
    count += 1
    print('\\')
    sleep(0.4)
    print('\n'*500)
    print('|')
    sleep(0.4)
    print('\n'*500)
    print('/')
    sleep(0.4)
    print('\n'*500)
    print('--')
    sleep(0.4)
    print('\n'*500)
    print('\\')
    sleep(0.4)
    print('\n'*500)
    print('|')
    sleep(0.4)
    print('\n'*500)
    print('/')
    sleep(0.4)
    print('\n'*500)
    print('--')
    sleep(0.4)
    print('\n'*500)
