<CustButton@Button>:
    font_size: 32
    color: 0, 0, 0, 1
    size: 150, 50
    background_normal: ''
    background_down: 0, 0, .50, 1
    background_color: .88, .88, .88, 1

    <CustomWidget>:
        CustButton:
            text:'Spam'
            pos: root.x, 200

        CustButton:
            text:'Spam'
            pos: 200, root.y

         CustButton:
            text:'Spam'
            pos: 400, 200